# Generated by Django 3.1.4 on 2020-12-10 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_auto_20201210_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='tag',
            new_name='tags',
        ),
    ]
